name: release
on:
  push:
    tags:
      - "v**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - runs: "npm ci"
      - runs: "npm run codegen"
      - runs: "node scripts/ci/ci-clear.mjs"
      - runs: "node scripts/ci/ci-build.mjs"
        env:
          NODE_ENV: "production"
      - runs: "node scripts/ci/ci-sign.mjs"
        env:
          MOZ_API_KEY: ${{ secrets.MOZ_API_KEY }}
          MOZ_API_SECRET: ${{ secrets.MOZ_API_SECRET }}
      - runs: "npm run release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
