name: test merges
on:
  pull_request_target:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_HEAD_REF: ${{ github.head_ref }}
      GITHUB_MERGED_STATUS: ${{ github.event.pull_request.merged }}
    steps:
    - run: |
        echo "${GITHUB_REF}" "${GITHUB_HEAD_REF}" "${GITHUB_MERGED_STATUS}"